// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ohd.Data;

#nullable disable

namespace Ohd.Migrations
{
    [DbContext(typeof(OhdDbContext))]
    partial class OhdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ohd.Entities.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UploadedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("attachments");
                });

            modelBuilder.Entity("Ohd.Entities.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("parent_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Ohd.Entities.Escalation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<long?>("notified_to_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("remarks")
                        .HasColumnType("longtext");

                    b.Property<long>("request_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("resolved_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("triggered_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("escalations");
                });

            modelBuilder.Entity("Ohd.Entities.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<long?>("HeadUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("head_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("facilities", (string)null);
                });

            modelBuilder.Entity("Ohd.Entities.MaintenanceWindow", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("end_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("facility_id")
                        .HasColumnType("int");

                    b.Property<string>("reason")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("maintenance_windows");
                });

            modelBuilder.Entity("Ohd.Entities.MfaSecret", b =>
                {
                    b.Property<long>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("user_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("secret_encrypted")
                        .HasColumnType("longblob");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("user_id");

                    b.HasIndex("userId");

                    b.ToTable("mfa_secrets");
                });

            modelBuilder.Entity("Ohd.Entities.Notification", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("is_read")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<long>("request_id")
                        .HasColumnType("bigint")
                        .HasColumnName("request_id");

                    b.Property<long>("sent_to_user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Ohd.Entities.OutboxMessage", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("attempts")
                        .HasColumnType("int");

                    b.Property<string>("body_html")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("last_attempt_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("recipient_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("outbox_messages");
                });

            modelBuilder.Entity("Ohd.Entities.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("Ohd.Entities.RateLimitBucket", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("bucket_key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("counter")
                        .HasColumnType("int");

                    b.Property<DateTime>("reset_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("rate_limit_buckets");
                });

            modelBuilder.Entity("Ohd.Entities.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssigneeId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("facility_id");

                    b.Property<bool>("FirstReminderSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastReminderAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("int")
                        .HasColumnName("priority_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<string>("RequesterEmail")
                        .HasColumnType("longtext");

                    b.Property<long>("RequestorId")
                        .HasColumnType("bigint")
                        .HasColumnName("requestor_id");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int")
                        .HasColumnName("severity_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SeverityId");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("Ohd.Entities.RequestCategory", b =>
                {
                    b.Property<long>("request_id")
                        .HasColumnType("bigint");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.HasKey("request_id", "category_id");

                    b.ToTable("request_categories");
                });

            modelBuilder.Entity("Ohd.Entities.RequestPriority", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("request_priorities");
                });

            modelBuilder.Entity("Ohd.Entities.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .HasColumnType("longtext")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_final");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_overdue");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("request_statuses", (string)null);
                });

            modelBuilder.Entity("Ohd.Entities.RequestStatusTransition", b =>
                {
                    b.Property<int>("from_status_id")
                        .HasColumnType("int");

                    b.Property<int>("to_status_id")
                        .HasColumnType("int");

                    b.HasKey("from_status_id", "to_status_id");

                    b.ToTable("request_status_transitions");
                });

            modelBuilder.Entity("Ohd.Entities.RequestTag", b =>
                {
                    b.Property<long>("request_id")
                        .HasColumnType("bigint");

                    b.Property<int>("tag_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("request_id", "tag_id");

                    b.ToTable("request_tags");
                });

            modelBuilder.Entity("Ohd.Entities.Request_Comments", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttachmentsCount")
                        .HasColumnType("int");

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("request_comments");
                });

            modelBuilder.Entity("Ohd.Entities.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Ohd.Entities.Severity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("FirstReminderMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RepeatReminderMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("auto_notify")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("notify_email_template_code")
                        .HasColumnType("longtext");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("severities");
                });

            modelBuilder.Entity("Ohd.Entities.Skills", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("Ohd.Entities.SystemSetting", b =>
                {
                    b.Property<string>("key")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("value_json")
                        .HasColumnType("longtext");

                    b.HasKey("key");

                    b.ToTable("system_settings");
                });

            modelBuilder.Entity("Ohd.Entities.Tags", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("Ohd.Entities.Teams", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("team_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("Ohd.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Is_First_Login")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("Password_Last_Changed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ohd.Entities.UserRoles", b =>
                {
                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("assigned_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("user_id", "role_id");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("Ohd.Entities.UserTeam", b =>
                {
                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<int>("team_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("joined_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("user_id", "team_id");

                    b.ToTable("user_teams");
                });

            modelBuilder.Entity("Ohd.Entities.audit_logs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("actor_user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("after_json")
                        .HasColumnType("longtext");

                    b.Property<string>("before_json")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("entity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("entity_id")
                        .HasColumnType("bigint");

                    b.Property<string>("ip")
                        .HasColumnType("longtext");

                    b.Property<string>("user_agent")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("Ohd.Entities.ip_blocklist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("blocked_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("reason")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("ip_blocklist");
                });

            modelBuilder.Entity("Ohd.Entities.password_history", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("changed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("password_hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("password_history");
                });

            modelBuilder.Entity("Ohd.Entities.password_reset_tokens", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("token_hash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("used_at")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("password_reset_tokens");
                });

            modelBuilder.Entity("Ohd.Entities.request_history", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("changed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("changed_by_user_id")
                        .HasColumnType("bigint");

                    b.Property<int?>("from_status_id")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .HasColumnType("longtext");

                    b.Property<long>("request_id")
                        .HasColumnType("bigint");

                    b.Property<int>("to_status_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("request_history");
                });

            modelBuilder.Entity("Ohd.Entities.role_permissions", b =>
                {
                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<int>("permission_id")
                        .HasColumnType("int");

                    b.HasKey("role_id", "permission_id");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("Ohd.Entities.sla_policies", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("category_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("facility_id")
                        .HasColumnType("int");

                    b.Property<int>("priority")
                        .HasColumnType("int");

                    b.Property<int>("resolve_within_mins")
                        .HasColumnType("int");

                    b.Property<int>("respond_within_mins")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("sla_policies");
                });

            modelBuilder.Entity("Ohd.Entities.user_sessions", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ip")
                        .HasColumnType("longtext");

                    b.Property<string>("jwt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("last_seen_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_agent")
                        .HasColumnType("longtext");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("Ohd.Entities.MfaSecret", b =>
                {
                    b.HasOne("Ohd.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Ohd.Entities.Request", b =>
                {
                    b.HasOne("Ohd.Entities.Severity", "Severity")
                        .WithMany()
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Severity");
                });
#pragma warning restore 612, 618
        }
    }
}
